### ISSUE TITLE
Image still available?

### ISSUE THREAD

**Issue by meetunix** [marcellussiegburg/autotool-tutorium#2]
The url http://autotool-test.imn.htwk-leipzig.de/hal2015/ seems to be empty. Is is possible to get the autotool-yesod image elsewehere?

**Comment by marcellussiegburg** [comment]
Yes, you can use the [autobuildtool](https://github.com/marcellussiegburg/autobuildtool). However, I am unsure, if it is working properly as the autotool building process originally implemented in the autobuildtool is superseded. But you may give it a try. (This is how the image was originally built)
